### ISSUE TITLE
caja-terminal reads and acts on old config file format, writes new but doesn't understand it

### ISSUE THREAD

**Issue by dwtokarski** [yselkowitz/caja-terminal#2]
Hi,
In Fedora 20 using caja-terminal 0.8, the preferences->colors settings could be used
to change the text and background colors. In Fedora 23 with caja-terminal 0.9 that no
longer works.

My old config file from Fedora 20 has this in it:

[COLOR]
        text = "#0fa5fe7a9996"
        background = "#000000"
        palettename = "Tango"

...and that results in the expected colors being rendered.

However, after using the preferences->colors settings to make a change, the
config file is written to have:

COLOR]
        text = "Gdk.Color(red=50372, green=41120, blue=0)"
        background = "#000000"
        palettename = "Tango"

This results in white text on a black background, and there it is stuck
until the config file is fixed by manual editing. After caja is killed to force
a reread, the desired colors are restored.

Looks like someone tried to update the config file format and only got
the job half done.

**Comment by raveit65** [comment]
@yselkowitz 
Can you please take a look into it ?

**Comment by yselkowitz** [comment]
This should be fixed in 0.9.1.
